name: Deploy DAG to Cloud Composer

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # Set this in GitHub Secrets

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: your-gcp-project-id  # Replace with your GCP project ID

    - name: Upload DAG to Cloud Composer
      run: |
        gsutil cp dags/etl_pyspark_bigquery.py gs://us-central1-sales-data-envi-b4a9e081-bucket/dags/
